#!/bin/csh
set EXCLUDES='#DSI3_channel_trimming_registers,#time_base_registers,#Interrupt_Registers,#buffer_interrupt_registers,#ring_buffer_registers,#SPI_registers,#IC_status_word,#DSI3_channel_registers,#common_DSI3_block_registers,#DSI3_wave_shaping_registers,#supply_registers,#IC_revision_and_ID_registers,#Standard_test_register,#OTP_Key_Register_8bit,#OTP_ECC_Control_Registers_8bit,#OTP_readout_register,#Test_Registers,#ELIP_test_register,#ATPG_test_register,#SRAM_BIST_registers,#scan_registers,#OTP_test_registers'
set TARGET_PATH=${DESIGN}/${DIGITAL}/stove
set OPTIONS = "-x $EXCLUDES -e .sv --gobbling structured"

## Operation_Mode_Control
set JSON = ${DESIGN}/${DIGITAL}/config/$PROJECT_STATE.json

echo "##### generating test register interfaces ##############################"
mkdir -p ${TARGET_PATH}/test_ifs
rm -rf ${TARGET_PATH}/test_ifs/*.*
stove edf-headers -p $JSON -o ${TARGET_PATH}/test_ifs  -t ${TARGET_PATH}/test_if.vm $OPTIONS
echo "##### generating test modules ##########################################"
mkdir -p ${TARGET_PATH}/test_modules
rm -rf ${TARGET_PATH}/test_modules/*.*
stove edf-headers -p $JSON -o ${TARGET_PATH}/test_modules -t ${TARGET_PATH}/test_modules.vm $OPTIONS
echo "########################################################################"

perl -pi -e 'undef $/; s/^\s*\n/\n/gs' test_*/*.sv

#remove empty interface from test_ws.sv
sed -i /tmr_ws_if/d ${TARGET_PATH}/test_modules/test_ws.sv
