////////////////////////////////////////////////////////////////
// Netlist generated by	: Custom Designer (TM) db::generateVerilog
// Date			: Thu Jul 20 13:51:40 CEST 2017
////////////////////////////////////////////////////////////////
// Library Name	:	 17402
// Cell Name	:	 CLKREF_LPF
// View Name	:	 systemverilog
////////////////////////////////////////////////////////////////

module CLKREF_LPF (CLKREF, CLKREF_FILT, GND, VDD);
       input CLKREF;
       output CLKREF_FILT;
       reg CLKREF_FILT;
       input GND;
       input VDD;
       
    always @(*) begin
      CLKREF_FILT = CLKREF;
    end
    
    specify
      //unit is ns
      (CLKREF => CLKREF_FILT)=(200, 200);
    endspecify
    
endmodule
