set_property MARK_DEBUG true [get_nets swclk]
set_property MARK_DEBUG true [get_nets swdi]
set_property MARK_DEBUG true [get_nets swdo]
set_property MARK_DEBUG true [get_nets swdo_e]
set_property MARK_DEBUG true [get_nets tst]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[5]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[13]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[7]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[30]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[10]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[21]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[3]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[27]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[14]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[12]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[9]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[8]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[18]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[7]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[9]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[28]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[25]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[11]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[17]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[16]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[23]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[22]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[15]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[31]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[5]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[26]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[14]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[4]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[1]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[0]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[2]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[0]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[13]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[19]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[20]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[24]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[29]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[6]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[8]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[10]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[11]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[12]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[15]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[16]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[17]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[18]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[19]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[1]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[20]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[21]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[22]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[23]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[24]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[25]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[26]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[27]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[28]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[29]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[2]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[30]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[31]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[3]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[4]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[5]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[6]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HSIZE[0]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HSIZE[1]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HSIZE[2]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HTRANS[0]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HTRANS[1]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[0]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[10]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[11]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[12]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[13]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[14]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[15]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[16]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[17]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[18]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[19]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[1]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[20]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[21]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[22]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[23]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[24]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[25]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[26]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[27]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[28]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[29]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[2]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[30]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[31]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[3]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[4]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[6]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[7]}]
set_property MARK_DEBUG true [get_nets {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[8]}]
set_property MARK_DEBUG true [get_nets digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HREADY]
set_property MARK_DEBUG true [get_nets digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWRITE]

set_property MARK_DEBUG true [get_nets s_adc_sdo]
set_property MARK_DEBUG true [get_nets s_adc_sck]
set_property MARK_DEBUG true [get_nets s_adc_conv]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[0]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[1]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[2]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[3]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[4]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[5]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[6]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[7]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[8]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[9]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[10]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[11]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[12]}]
set_property MARK_DEBUG true [get_nets {adc_ch0_out[13]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[0]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[1]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[2]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[3]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[4]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[5]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[6]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[7]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[8]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[9]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[10]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[11]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[12]}]
set_property MARK_DEBUG true [get_nets {adc_ch1_out[13]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]

set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_pins bufg_clk_clk_48_n/O]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HREADY digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWRITE]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[0]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[1]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[2]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[3]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[4]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[5]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[6]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[7]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[8]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[9]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[10]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[11]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[12]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[13]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[14]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[15]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[16]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[17]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[18]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[19]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[20]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[21]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[22]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[23]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[24]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[25]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[26]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[27]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[28]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[29]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[30]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HADDR[31]}]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[0]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[1]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[2]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[3]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[4]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[5]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[6]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[7]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[8]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[9]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[10]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[11]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[12]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[13]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[14]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[15]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[16]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[17]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[18]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[19]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[20]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[21]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[22]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[23]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[24]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[25]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[26]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[27]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[28]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[29]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[30]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HRDATA[31]}]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[0]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[1]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[2]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[3]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[4]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[5]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[6]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[7]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[8]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[9]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[10]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[11]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[12]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[13]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[14]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[15]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[16]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[17]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[18]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[19]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[20]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[21]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[22]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[23]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[24]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[25]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[26]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[27]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[28]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[29]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[30]} {digital_inst/core_inst/cpu_core_sys_inst/acm0_inst/AHBL_BUS_HWDATA[31]}]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 5 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list tst swclk swdi swdo swdo_e]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list s_adc_sdo s_adc_sck s_adc_conv]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 14 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {adc_ch0_out[0]} {adc_ch0_out[1]} {adc_ch0_out[2]} {adc_ch0_out[3]} {adc_ch0_out[4]} {adc_ch0_out[5]} {adc_ch0_out[6]} {adc_ch0_out[7]} {adc_ch0_out[8]} {adc_ch0_out[9]} {adc_ch0_out[10]} {adc_ch0_out[11]} {adc_ch0_out[12]} {adc_ch0_out[13]} ]]

create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 14 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {adc_ch1_out[0]} {adc_ch1_out[1]} {adc_ch1_out[2]} {adc_ch1_out[3]} {adc_ch1_out[4]} {adc_ch1_out[5]} {adc_ch1_out[6]} {adc_ch1_out[7]} {adc_ch1_out[8]} {adc_ch1_out[9]} {adc_ch1_out[10]} {adc_ch1_out[11]} {adc_ch1_out[12]} {adc_ch1_out[13]} ]]



set_property C_CLK_INPUT_FREQ_HZ 48000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_pins bufg_clk_clk_48_n/O]
