// includes
+incdir+${DESIGN}/${DIGITAL}/config
+incdir+${DESIGN}/${DIGITAL}/edf_registers/
+incdir+${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/
+incdir+${SYNOPSYS}/dw/sim_ver/
+incdir+${DESIGN}/${DIGITAL}/ECC/rtl

//Packages
${DESIGN}/${DIGITAL}/rtl/project_pkg.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_pkg.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_pkg.sv
${DESIGN}/${DIGITAL}/DATA_STORAGE/rtl/buffer_if_pkg.sv
${DESIGN}/${DIGITAL}/SPI/rtl/spi_implementation_pkg.sv

//Interfaces
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_common_config_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_io_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tmr_dsi_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tmr_out_dsi_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_start_request_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/synchronization_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/general_data_writer_inputs.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_reader_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_spi_reader_if.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_writer_if.sv

//Modules
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_interface.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_packet_ecc_check.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_header_ecc_check.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_ecc_check.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_buffer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_manager.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_spi_reader_demux.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tdma_scheme_visualizer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_crc_parallel_symbol.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_crc_parallel.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_chip_converter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_chip_filter_for_dm.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_chip_filter_counter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_filter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive_filter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive_counter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive_sample_counter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive_sampling.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive_data_collect.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_receive.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_start_tick_gater.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_start_manager.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_start_tick_generator.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_symbol_builder.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_symbol_lut.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_transmit.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_iload_control.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/enable_counter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/packet_stat_multiplexer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/period_counter.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/test_ws.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_wave_shaping.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_crm_data_writer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_pdcm_data_writer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/frame_data_visualizer.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_core.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/shift_generator.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/tbit_generator.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/txshift_controller.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/synchronization_manager_block.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/synchronization_manager.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_sync_master.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/test_dsi.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3_block.sv
${DESIGN}/${DIGITAL}/DSI3_MASTER/rtl/dsi3.sv
