${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/ip/xilinx.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_and.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_and3.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_and4.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_buf.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_clk_gate_latch.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_delay.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_ff.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_inv.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_mask.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_mux.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_mux4.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_nand.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_or.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_or3.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/pure_or4.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/iopad.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/ipad.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/opad.v
${DESIGN}/${DIGITAL}/tech/XILINX_UNISIM/hdl/sync_sram.sv
