//==================================================
// Copyright (c) 2023 Elmos SE
// Author: stove
// Description : Note: This file has been generated automatically by stove
//               Note: This file should not be modified manually.
//               This file contains the Excluded objects
//==================================================
  


INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_TRIM_IREF
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_TRIM_IREF [4] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [5] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [6] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [7] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [8] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [9] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [10] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [11] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [12] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [13] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [14] "logic data_out_TRIM_IREF[15:0]"
Toggle data_out_TRIM_IREF [15] "logic data_out_TRIM_IREF[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_TRIM_IREF
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_TRIM_OT
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_TRIM_OT [2] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [3] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [4] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [5] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [6] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [7] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [8] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [9] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [10] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [11] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [12] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [13] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [14] "logic data_out_TRIM_OT[15:0]"
Toggle data_out_TRIM_OT [15] "logic data_out_TRIM_OT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_TRIM_OT
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_SUP_HW_CTRL
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_SUP_HW_CTRL [2] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [3] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [4] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [5] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [6] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [7] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [8] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [9] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [10] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [11] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [12] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [13] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [14] "logic data_out_SUP_HW_CTRL[15:0]"
Toggle data_out_SUP_HW_CTRL [15] "logic data_out_SUP_HW_CTRL[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_SUP_HW_CTRL
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_SUP_IRQ_STAT
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_SUP_IRQ_STAT [5] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [6] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [7] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [8] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [9] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [10] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [11] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [12] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [13] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [14] "logic data_out_SUP_IRQ_STAT[15:0]"
Toggle data_out_SUP_IRQ_STAT [15] "logic data_out_SUP_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_SUP_IRQ_STAT
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_SUP_IRQ_MASK
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_SUP_IRQ_MASK [5] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [6] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [7] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [8] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [9] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [10] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [11] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [12] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [13] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [14] "logic data_out_SUP_IRQ_MASK[15:0]"
Toggle data_out_SUP_IRQ_MASK [15] "logic data_out_SUP_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_SUP_IRQ_MASK
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_SUP_STAT
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_SUP_STAT [5] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [6] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [7] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [8] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [9] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [10] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [11] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [12] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [13] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [14] "logic data_out_SUP_STAT[15:0]"
Toggle data_out_SUP_STAT [15] "logic data_out_SUP_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_SUP_STAT
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_SUP_CTRL
Toggle value [1] "logic value[15:0]"
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_SUP_CTRL [1] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [2] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [3] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [4] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [5] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [6] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [7] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [8] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [9] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [10] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [11] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [12] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [13] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [14] "logic data_out_SUP_CTRL[15:0]"
Toggle data_out_SUP_CTRL [15] "logic data_out_SUP_CTRL[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_SUP_CTRL
Toggle data_out [1] "logic data_out[15:0]"
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.supply_registers_IO_CTRL
Toggle value [1] "logic value[15:0]"
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out_IO_CTRL [1] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [2] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [3] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [4] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [5] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [6] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [7] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [8] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [9] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [10] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [11] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [12] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [13] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [14] "logic data_out_IO_CTRL[15:0]"
Toggle data_out_IO_CTRL [15] "logic data_out_IO_CTRL[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers.i_supply_registers_IO_CTRL
Toggle data_out [1] "logic data_out[15:0]"
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_supply_registers
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.time_base_registers_CLKREF_CONF
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers
Toggle data_out_CLKREF_CONF [2] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [3] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [4] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [5] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [6] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [7] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [8] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [9] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [10] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [11] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [12] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [13] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [14] "logic data_out_CLKREF_CONF[15:0]"
Toggle data_out_CLKREF_CONF [15] "logic data_out_CLKREF_CONF[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers.i_time_base_registers_CLKREF_CONF
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.time_base_registers_TRIM_OSC
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers
Toggle data_out_TRIM_OSC [7] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [8] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [9] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [10] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [11] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [12] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [13] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [14] "logic data_out_TRIM_OSC[15:0]"
Toggle data_out_TRIM_OSC [15] "logic data_out_TRIM_OSC[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers.i_time_base_registers_TRIM_OSC
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.time_base_registers_TRIM_OSC_TCF
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers
Toggle data_out_TRIM_OSC_TCF [3] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [4] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [5] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [6] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [7] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [8] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [9] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [10] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [11] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [12] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [13] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [14] "logic data_out_TRIM_OSC_TCF[15:0]"
Toggle data_out_TRIM_OSC_TCF [15] "logic data_out_TRIM_OSC_TCF[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_timebase.i_time_base_registers.i_time_base_registers_TRIM_OSC_TCF
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_IRQ_STAT
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_IRQ_STAT [7] "logic data_out_IRQ_STAT[15:0]"
Toggle data_out_IRQ_STAT [8] "logic data_out_IRQ_STAT[15:0]"
Toggle data_out_IRQ_STAT [13] "logic data_out_IRQ_STAT[15:0]"
Toggle data_out_IRQ_STAT [14] "logic data_out_IRQ_STAT[15:0]"
Toggle data_out_IRQ_STAT [15] "logic data_out_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_IRQ_STAT
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_IRQ_MASK
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_IRQ_MASK [7] "logic data_out_IRQ_MASK[15:0]"
Toggle data_out_IRQ_MASK [8] "logic data_out_IRQ_MASK[15:0]"
Toggle data_out_IRQ_MASK [13] "logic data_out_IRQ_MASK[15:0]"
Toggle data_out_IRQ_MASK [14] "logic data_out_IRQ_MASK[15:0]"
Toggle data_out_IRQ_MASK [15] "logic data_out_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_IRQ_MASK
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_ECC_IRQ_STAT
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_ECC_IRQ_STAT [10] "logic data_out_ECC_IRQ_STAT[15:0]"
Toggle data_out_ECC_IRQ_STAT [11] "logic data_out_ECC_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_ECC_IRQ_STAT
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_ECC_IRQ_MASK
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_ECC_IRQ_MASK [10] "logic data_out_ECC_IRQ_MASK[15:0]"
Toggle data_out_ECC_IRQ_MASK [11] "logic data_out_ECC_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_ECC_IRQ_MASK
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_ECC_CORR_IRQ_STAT
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_ECC_CORR_IRQ_STAT [10] "logic data_out_ECC_CORR_IRQ_STAT[15:0]"
Toggle data_out_ECC_CORR_IRQ_STAT [11] "logic data_out_ECC_CORR_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_ECC_CORR_IRQ_STAT
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.Interrupt_Registers_ECC_CORR_IRQ_MASK
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers
Toggle data_out_ECC_CORR_IRQ_MASK [10] "logic data_out_ECC_CORR_IRQ_MASK[15:0]"
Toggle data_out_ECC_CORR_IRQ_MASK [11] "logic data_out_ECC_CORR_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_Interrupt_Registers.i_Interrupt_Registers_ECC_CORR_IRQ_MASK
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.buffer_interrupt_registers_BUF_IRQ_STAT
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers
Toggle data_out_BUF_IRQ_STAT [7] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [8] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [9] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [10] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [11] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [12] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [13] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [14] "logic data_out_BUF_IRQ_STAT[15:0]"
Toggle data_out_BUF_IRQ_STAT [15] "logic data_out_BUF_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers.i_buffer_interrupt_registers_BUF_IRQ_STAT
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.buffer_interrupt_registers_BUF_IRQ_MASK
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers
Toggle data_out_BUF_IRQ_MASK [7] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [8] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [9] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [10] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [11] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [12] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [13] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [14] "logic data_out_BUF_IRQ_MASK[15:0]"
Toggle data_out_BUF_IRQ_MASK [15] "logic data_out_BUF_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers.i_buffer_interrupt_registers_BUF_IRQ_MASK
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.buffer_interrupt_registers_BUF_FILL_WARN
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers
Toggle data_out_BUF_FILL_WARN [7] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [8] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [9] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [10] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [11] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [12] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [13] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [14] "logic data_out_BUF_FILL_WARN[15:0]"
Toggle data_out_BUF_FILL_WARN [15] "logic data_out_BUF_FILL_WARN[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers.i_buffer_interrupt_registers_BUF_FILL_WARN
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_buffer_interrupt_registers
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.SPI_registers_SPI_IRQ_STAT
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers
Toggle data_out_SPI_IRQ_STAT [5] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [6] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [7] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [8] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [9] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [10] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [11] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [12] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [13] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [14] "logic data_out_SPI_IRQ_STAT[15:0]"
Toggle data_out_SPI_IRQ_STAT [15] "logic data_out_SPI_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers.i_SPI_registers_SPI_IRQ_STAT
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.SPI_registers_SPI_IRQ_MASK
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers
Toggle data_out_SPI_IRQ_MASK [5] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [6] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [7] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [8] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [9] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [10] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [11] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [12] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [13] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [14] "logic data_out_SPI_IRQ_MASK[15:0]"
Toggle data_out_SPI_IRQ_MASK [15] "logic data_out_SPI_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers.i_SPI_registers_SPI_IRQ_MASK
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.SPI_registers_STATUS_WORD
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers
Toggle data_out_STATUS_WORD [4] "logic data_out_STATUS_WORD[15:0]"
Toggle data_out_STATUS_WORD [5] "logic data_out_STATUS_WORD[15:0]"
Toggle data_out_STATUS_WORD [6] "logic data_out_STATUS_WORD[15:0]"
Toggle data_out_STATUS_WORD [7] "logic data_out_STATUS_WORD[15:0]"
Toggle data_out_STATUS_WORD [8] "logic data_out_STATUS_WORD[15:0]"
Toggle data_out_STATUS_WORD [9] "logic data_out_STATUS_WORD[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers.i_SPI_registers_STATUS_WORD
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_spi.i_SPI_registers
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_DSI_ENABLE
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_DSI_ENABLE [2] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [3] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [4] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [5] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [6] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [7] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [8] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [9] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [10] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [11] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [12] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [13] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [14] "logic data_out_DSI_ENABLE[15:0]"
Toggle data_out_DSI_ENABLE [15] "logic data_out_DSI_ENABLE[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_DSI_ENABLE
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_DSI_CFG
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_DSI_CFG [7] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [8] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [9] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [10] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [11] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [12] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [13] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [14] "logic data_out_DSI_CFG[15:0]"
Toggle data_out_DSI_CFG [15] "logic data_out_DSI_CFG[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_DSI_CFG
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_DSI_TX_SHIFT
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_DSI_TX_SHIFT [7] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [8] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [9] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [10] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [11] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [12] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [13] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [14] "logic data_out_DSI_TX_SHIFT[15:0]"
Toggle data_out_DSI_TX_SHIFT [15] "logic data_out_DSI_TX_SHIFT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_DSI_TX_SHIFT
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_SYNC_IDLE_REG
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_SYNC_IDLE_REG [2] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [3] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [4] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [5] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [6] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [7] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [8] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [9] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [10] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [11] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [12] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [13] "logic data_out_SYNC_IDLE_REG[15:0]"
Toggle data_out_SYNC_IDLE_REG [14] "logic data_out_SYNC_IDLE_REG[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_SYNC_IDLE_REG
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_CRM_TIME
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_CRM_TIME [11] "logic data_out_CRM_TIME[15:0]"
Toggle data_out_CRM_TIME [12] "logic data_out_CRM_TIME[15:0]"
Toggle data_out_CRM_TIME [13] "logic data_out_CRM_TIME[15:0]"
Toggle data_out_CRM_TIME [14] "logic data_out_CRM_TIME[15:0]"
Toggle data_out_CRM_TIME [15] "logic data_out_CRM_TIME[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_CRM_TIME
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.common_DSI3_block_registers_CRM_TIME_NR
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out_CRM_TIME_NR [11] "logic data_out_CRM_TIME_NR[15:0]"
Toggle data_out_CRM_TIME_NR [12] "logic data_out_CRM_TIME_NR[15:0]"
Toggle data_out_CRM_TIME_NR [13] "logic data_out_CRM_TIME_NR[15:0]"
Toggle data_out_CRM_TIME_NR [14] "logic data_out_CRM_TIME_NR[15:0]"
Toggle data_out_CRM_TIME_NR [15] "logic data_out_CRM_TIME_NR[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers.i_common_DSI3_block_registers_CRM_TIME_NR
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_common_DSI3_block_registers
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.OTP_readout_register_OTP_READ_ADDRESS
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register
Toggle data_out_OTP_READ_ADDRESS [12] "logic data_out_OTP_READ_ADDRESS[15:0]"
Toggle data_out_OTP_READ_ADDRESS [13] "logic data_out_OTP_READ_ADDRESS[15:0]"
Toggle data_out_OTP_READ_ADDRESS [14] "logic data_out_OTP_READ_ADDRESS[15:0]"
Toggle data_out_OTP_READ_ADDRESS [15] "logic data_out_OTP_READ_ADDRESS[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register.i_OTP_readout_register_OTP_READ_ADDRESS
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.OTP_readout_register_OTP_READ_VALUE
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register
Toggle data_out_OTP_READ_VALUE [12] "logic data_out_OTP_READ_VALUE[15:0]"
Toggle data_out_OTP_READ_VALUE [13] "logic data_out_OTP_READ_VALUE[15:0]"
Toggle data_out_OTP_READ_VALUE [14] "logic data_out_OTP_READ_VALUE[15:0]"
Toggle data_out_OTP_READ_VALUE [15] "logic data_out_OTP_READ_VALUE[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register.i_OTP_readout_register_OTP_READ_VALUE
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.OTP_readout_register_OTP_READ_STATUS
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [4] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register
Toggle data_out_OTP_READ_STATUS [2] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [3] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [4] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [5] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [6] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [7] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [8] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [9] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [10] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [11] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [12] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [13] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [14] "logic data_out_OTP_READ_STATUS[15:0]"
Toggle data_out_OTP_READ_STATUS [15] "logic data_out_OTP_READ_STATUS[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register.i_OTP_readout_register_OTP_READ_STATUS
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [4] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_main_control.i_main_fsm.i_otp_reader.i_OTP_readout_register
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_trimming_registers_TRIM_DSI_REC_FALL
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out_TRIM_DSI_REC_FALL [8] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [9] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [10] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [11] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [12] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [13] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [14] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [15] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_trimming_registers.i_DSI3_channel_trimming_registers_TRIM_DSI_REC_FALL
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_trimming_registers_TRIM_DSI_REC_RISE
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out_TRIM_DSI_REC_RISE [8] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [9] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [10] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [11] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [12] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [13] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [14] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [15] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_trimming_registers.i_DSI3_channel_trimming_registers_TRIM_DSI_REC_RISE
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_trimming_registers_TRIM_DSI_REC_FALL
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out_TRIM_DSI_REC_FALL [8] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [9] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [10] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [11] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [12] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [13] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [14] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
Toggle data_out_TRIM_DSI_REC_FALL [15] "logic data_out_TRIM_DSI_REC_FALL[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_trimming_registers.i_DSI3_channel_trimming_registers_TRIM_DSI_REC_FALL
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_trimming_registers_TRIM_DSI_REC_RISE
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out_TRIM_DSI_REC_RISE [8] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [9] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [10] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [11] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [12] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [13] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [14] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
Toggle data_out_TRIM_DSI_REC_RISE [15] "logic data_out_TRIM_DSI_REC_RISE[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_trimming_registers.i_DSI3_channel_trimming_registers_TRIM_DSI_REC_RISE
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_trimming_registers
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_DSI_STAT
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_STAT [15] "logic data_out_DSI_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_STAT
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_DSI_LOAD
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_LOAD [5] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [6] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [7] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [8] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [9] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [10] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [11] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [12] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [13] "logic data_out_DSI_LOAD[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_LOAD
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_DSI_IRQ_STAT
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_IRQ_STAT [7] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [8] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [9] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [10] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [11] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [12] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [13] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [14] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [15] "logic data_out_DSI_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_IRQ_STAT
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_DSI_IRQ_MASK
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_IRQ_MASK [7] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [8] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [9] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [10] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [11] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [12] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [13] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [14] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [15] "logic data_out_DSI_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_IRQ_MASK
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_PACKET_STAT
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_PACKET_STAT [14] "logic data_out_PACKET_STAT[15:0]"
Toggle data_out_PACKET_STAT [15] "logic data_out_PACKET_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_PACKET_STAT
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_FRAME_STAT
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_FRAME_STAT [8] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [9] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [10] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [11] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [12] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [13] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [14] "logic data_out_FRAME_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_FRAME_STAT
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_WAIT_TIME
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_WAIT_TIME [15] "logic data_out_WAIT_TIME[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_WAIT_TIME
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.DSI3_channel_registers_SYNC
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_SYNC [2] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [3] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [5] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [6] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [7] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [8] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [9] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [10] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [11] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [12] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [13] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [14] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [15] "logic data_out_SYNC[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[0].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_SYNC
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_DSI_STAT
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_STAT [15] "logic data_out_DSI_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_STAT
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_DSI_LOAD
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_LOAD [5] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [6] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [7] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [8] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [9] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [10] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [11] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [12] "logic data_out_DSI_LOAD[15:0]"
Toggle data_out_DSI_LOAD [13] "logic data_out_DSI_LOAD[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_LOAD
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_DSI_IRQ_STAT
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_IRQ_STAT [7] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [8] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [9] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [10] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [11] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [12] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [13] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [14] "logic data_out_DSI_IRQ_STAT[15:0]"
Toggle data_out_DSI_IRQ_STAT [15] "logic data_out_DSI_IRQ_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_IRQ_STAT
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_DSI_IRQ_MASK
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_DSI_IRQ_MASK [7] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [8] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [9] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [10] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [11] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [12] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [13] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [14] "logic data_out_DSI_IRQ_MASK[15:0]"
Toggle data_out_DSI_IRQ_MASK [15] "logic data_out_DSI_IRQ_MASK[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_DSI_IRQ_MASK
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_PACKET_STAT
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_PACKET_STAT [14] "logic data_out_PACKET_STAT[15:0]"
Toggle data_out_PACKET_STAT [15] "logic data_out_PACKET_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_PACKET_STAT
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_FRAME_STAT
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_FRAME_STAT [8] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [9] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [10] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [11] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [12] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [13] "logic data_out_FRAME_STAT[15:0]"
Toggle data_out_FRAME_STAT [14] "logic data_out_FRAME_STAT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_FRAME_STAT
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_WAIT_TIME
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_WAIT_TIME [15] "logic data_out_WAIT_TIME[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_WAIT_TIME
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.DSI3_channel_registers_SYNC
Toggle value [2] "logic value[15:0]"
Toggle value [3] "logic value[15:0]"
Toggle value [5] "logic value[15:0]"
Toggle value [6] "logic value[15:0]"
Toggle value [7] "logic value[15:0]"
Toggle value [8] "logic value[15:0]"
Toggle value [9] "logic value[15:0]"
Toggle value [10] "logic value[15:0]"
Toggle value [11] "logic value[15:0]"
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers
Toggle data_out_SYNC [2] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [3] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [5] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [6] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [7] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [8] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [9] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [10] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [11] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [12] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [13] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [14] "logic data_out_SYNC[15:0]"
Toggle data_out_SYNC [15] "logic data_out_SYNC[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.generate_dsi3_blocks[1].i_dsi3_block.i_DSI3_channel_registers.i_DSI3_channel_registers_SYNC
Toggle data_out [2] "logic data_out[15:0]"
Toggle data_out [3] "logic data_out[15:0]"
Toggle data_out [5] "logic data_out[15:0]"
Toggle data_out [6] "logic data_out[15:0]"
Toggle data_out [7] "logic data_out[15:0]"
Toggle data_out [8] "logic data_out[15:0]"
Toggle data_out [9] "logic data_out[15:0]"
Toggle data_out [10] "logic data_out[15:0]"
Toggle data_out [11] "logic data_out[15:0]"
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_command_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_command_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.i_command_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_command_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_command_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_command_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_command_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_command_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_command_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_crm_data_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_crm_data_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_crm_data_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_crm_data_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_crm_data_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_crm_data_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_pdcm_data_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_pdcm_data_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[0].i_dsi3_pdcm_data_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_pdcm_data_buffer.ring_buffer_registers_BUF_VALID_COUNT
Toggle value [12] "logic value[15:0]"
Toggle value [13] "logic value[15:0]"
Toggle value [14] "logic value[15:0]"
Toggle value [15] "logic value[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_pdcm_data_buffer.i_ring_buffer_registers
Toggle data_out_BUF_VALID_COUNT [12] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [13] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [14] "logic data_out_BUF_VALID_COUNT[15:0]"
Toggle data_out_BUF_VALID_COUNT [15] "logic data_out_BUF_VALID_COUNT[15:0]"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_buffers.generate_dsi_buffers[1].i_dsi3_pdcm_data_buffer.i_ring_buffer_registers.i_ring_buffer_registers_BUF_VALID_COUNT
Toggle data_out [12] "logic data_out[15:0]"
Toggle data_out [13] "logic data_out[15:0]"
Toggle data_out [14] "logic data_out[15:0]"
Toggle data_out [15] "logic data_out[15:0]"
