* StarRC Bridge Canidate Extraction

define(IN,`$1_$2')dnl
BLOCK:  chip_finish_icc
MILKYWAY_DATABASE: ../layout/IN(TOPLEVEL,LIB)
TCAD_GRD_FILE: TCAD
MAPPING_FILE:  MAP
EXTRACTION: C
COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
COUPLING_REPORT_FILE: results/bridge.file
COUPLING_ABS_THRESHOLD: 1e-15
COUPLING_REL_THRESHOLD: 0.1
COUPLING_REPORT_NUMBER: 1000


