#!/bin/csh

source env

##------------------------------------------------
## Main
##------------------------------------------------

#setenv IC_VER "M52144A"

##----------

$SPSCR_COMMON/run_sim  sup_tmin_c0  batch
$SPSCR_COMMON/run_sim  sup_tmax_c0  batch

$SPSCR_COMMON/run_sim  dsi_1ch_tmin_c0  batch
$SPSCR_COMMON/run_sim  dsi_1ch_tmax_c0  batch

##------------------------------------------------
##------------------------------------------------


