#!/bin/csh

source env

##------------------------------------------------
## Main
##------------------------------------------------

#setenv IC_VER "M52144A"

##----------

$SPSCR_COMMON/run_sim  start    batch
$SPSCR_COMMON/run_sim  sup      batch
$SPSCR_COMMON/run_sim  spi      batch
$SPSCR_COMMON/run_sim  timebase batch
$SPSCR_COMMON/run_sim  dsi      batch
#$SPSCR_COMMON/run_sim  eme      batch
#$SPSCR_COMMON/run_sim  emi      batch

##------------------------------------------------
##------------------------------------------------


