
 set_ungroup [get_cells {  i_IC_revision_and_ID_registers*}  -hier] true
set_ungroup [get_cells {  i_supply_registers*}  -hier] true
set_ungroup [get_cells {  i_time_base_registers*}  -hier] true
set_ungroup [get_cells {  i_Interrupt_Registers*}  -hier] true
set_ungroup [get_cells {  i_buffer_interrupt_registers*}  -hier] true
set_ungroup [get_cells {  i_SPI_registers*}  -hier] true
set_ungroup [get_cells {  i_common_DSI3_block_registers*}  -hier] true
set_ungroup [get_cells {  i_OTP_readout_register*}  -hier] true
set_ungroup [get_cells {  i_DSI3_channel_trimming_registers*}  -hier] true
set_ungroup [get_cells {  i_DSI3_channel_registers*}  -hier] true
set_ungroup [get_cells {  i_ring_buffer_registers*}  -hier] true
 set_ungroup [get_cells {  i_TEST_TOP*}  -hier] true
set_ungroup [get_cells {  i_TEST_SUPPLY*}  -hier] true
set_ungroup [get_cells {  i_TEST_OSC*}  -hier] true
set_ungroup [get_cells {  i_TEST_DSI*}  -hier] true
set_ungroup [get_cells {  i_scan_registers*}  -hier] true
set_ungroup [get_cells {  i_SRAM_BIST_registers*}  -hier] true
set_ungroup [get_cells {  i_OTP_test_registers*}  -hier] true
set_ungroup [get_cells {  i_TEST_WS*}  -hier] true
