#!/bin/sh

##------------------------------------------------
## Main
##------------------------------------------------

#IC_VER="MAIN"; export IC_VER

##----------

./run_sim  all_c0    batch
./run_sim  all_c1    batch
./run_sim  all_c2    batch
./run_sim  all_c3    batch
./run_sim  all_c4    batch

#/run_sim  all_mc1   batch
#/run_sim  all_mc2   batch
#/run_sim  all_mc3   batch

./run_sim  all       doc&

##------------------------------------------------
##------------------------------------------------


