//==================================================
// This file contains the Excluded objects
// Generated By User: jvoi
// Format Version: 2
// Date: Tue Jun  6 08:57:09 2023
// ExclMode: default
//==================================================
CHECKSUM: "522885067 3868825003"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_dsi3.i_wave_shaping
Toggle LUT "logic [4:0]LUT[0:1][0:71]"
CHECKSUM: "4188638018 1780651243"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.elip_write_register
Toggle rd "logic rd"
Toggle addr [15] "logic addr[15:0]"
Toggle addr [12] "logic addr[15:0]"
Toggle addr [13] "logic addr[15:0]"
Toggle addr [14] "logic addr[15:0]"
Toggle data_read.ecc "logic data_read.ecc[5:0]"
Toggle data_read.data "logic data_read.data[15:0]"
CHECKSUM: "4188638018 1780651243"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.elip_spi_read
Toggle wr "logic wr"
Toggle addr [15] "logic addr[15:0]"
Toggle addr [12] "logic addr[15:0]"
Toggle addr [13] "logic addr[15:0]"
Toggle addr [14] "logic addr[15:0]"
Toggle data_write.ecc "logic data_write.ecc[5:0]"
Toggle data_write.data "logic data_write.data[15:0]"
CHECKSUM: "747854964 2322289702"
INSTANCE: top_tb.th.i_dut_wrapper.xtop.xdigtop.i_logic_top.i_test.i_test_control.i_otp_wrapper.U_OTPWRAP_L3_TOP.U_OTPWRAP_L2_CPU.U_OTPWRAP_L1_JTAG.U_OTPWRAP_L0_ATPG.GEN_TSMC.U_OTP4KX12.u_otp4kx12.core
Toggle rom "reg [11:0]rom[0:4095]"
Toggle err "reg [11:0]err[0:4095]"
Toggle otp "reg [11:0]otp[0:4095]"
