#!/bin/sh

##------------------------------------------------
## Main
##------------------------------------------------

#IC_VER="MAIN"; export IC_VER

##----------

run_sim_corner () {

  #/run_sim  sup$1          batch
  #/run_sim  dsi$1          batch
  ./run_sim  timebase$1     batch
  #/run_sim  pads$1         batch
  #/run_sim  atpg$1         batch
  #/run_sim  atpg_nofloat$1 batch

}

##----------

run_sim_temp () {

  run_sim_corner "$1_c0"
  run_sim_corner "$1_c1"
  run_sim_corner "$1_c2"
  run_sim_corner "$1_c3"
  run_sim_corner "$1_c4"

}

##----------

run_sim_temp "_tmin"
#run_sim_temp "_ttyp"
run_sim_temp "_tmax"

##------------------------------------------------
##------------------------------------------------


